export function countryList() {
  return [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua &amp; Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia &amp; Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Cape Verde",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote D Ivoire",
    "Croatia",
    "Cruise Ship",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "French West Indies",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Kyrgyz Republic",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Pierre &amp; Miquelon",
    "Samoa",
    "San Marino",
    "Satellite",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "St Kitts &amp; Nevis",
    "St Lucia",
    "St Vincent",
    "St. Lucia",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor L'Este",
    "Togo",
    "Tonga",
    "Trinidad &amp; Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks &amp; Caicos",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (US)",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];
}

export function searchFilters() {
  return [
    {
      name: "Breakfast",
      type: "meal",
      dbName: "breakfast",
      active: false,
      cuisine: false,
    },
    {
      name: "Drinks",
      type: "meal",
      dbName: "drinks",
      active: false,
      cuisine: false,
    },
    {
      name: "Treats",
      type: "meal",
      dbName: "treats",
      active: false,
      cuisine: false,
    },

    {
      name: "Speedy",
      type: "time",
      dbName: 1,
      active: false,
      cuisine: false,
    },
    {
      name: "Gluten Free",
      type: "dietary",
      dbName: "gluten_free",
      active: false,
      cuisine: false,
    },
    {
      name: "High Protein",
      type: "dietary",
      dbName: "high_protein",
      active: false,
      cuisine: false,
    },
    {
      name: "Inspiration",
      type: "dropdown",
      dbName: "inspiration",
      active: false,
      cuisine: false,
    },
    {
      name: "Cuisines",
      type: "dropdown",
      dbName: "cuisines",
      active: false,
      cuisine: false,
    },
    {
      name: "Macros",
      type: "dropdown",
      dbName: "macros",
      active: false,
      cuisine: false,
    },
    {
      name: "Avoid ingredients",
      type: "dropdown",
      dbName: "avoid",
      active: false,
      cuisine: false,
    },
    {
      name: "Asian",
      type: "cuisine",
      dbName: "east_asian",
      active: false,
      cuisine: true,
    },
    {
      name: "Indian",
      type: "cuisine",
      dbName: "indian",
      active: false,
      cuisine: true,
    },
    {
      name: "Mexican",
      type: "cuisine",
      dbName: "mexican",
      active: false,
      cuisine: true,
    },
    {
      name: "Italian",
      type: "cuisine",
      dbName: "italian",
      active: false,
      cuisine: true,
    },
    {
      name: "Caribbean",
      type: "cuisine",
      dbName: "caribbean",
      active: false,
      cuisine: true,
    },
    {
      name: "European",
      type: "cuisine",
      dbName: "european",
      active: false,
      cuisine: true,
    },
    {
      name: "Middle Eastern",
      type: "cuisine",
      dbName: "middle_east",
      active: false,
      cuisine: true,
    },
  ];
}

export function fetchInspiration() {
  return {
    breakfast: [
      "oats",
      "porridge",
      "toast",
      "pancakes",
      "breakfast burrito",
      "tofu scramble",
      "bagel",
      "smoothie bowl",
      "frittata",
      "oatmeal",
      "hash",
      "waffles",
      "muesli",
      "full english",
      "omelette",
      "french toast",
      "breakfast muffins",
      "breakfast bars",
      "benedict",
      "cinnamon rolls",
      "bacon",
      "crepes",
      "parfait",
      "huevos rancheros",
      "minestrone",
      "orzo",
    ],
    lunch: [
      "salad",
      "baguette",
      "sandwich",
      "wraps",
      "soup",
      "buddha bowl",
      "pasta",
      "curry",
      "tacos",
      "tabbouleh",
      "falafel",
      "burrito",
      "dal",
      "pita",
      "bagel",
      "couscous",
      "poke",
      "bisque",
      "bao",
      "saag",
      "shawarma",
      "sushi rolls",
      "quinoa",
      "bowl",
      "rice paper rolls",
      "gyros",
      "pesto pasta",
      "crostini",
      "gazpacho",
      "panzanella",
    ],
    dinner: [
      "pizza",
      "curry",
      "thai curry",
      "lasagna",
      "burgers",
      "shepherd's pie",
      "burritos",
      "tacos",
      "stew",
      "chilli",
      "pasta",
      "spaghetti",
      "meat balls",
      "bolognese",
      "pad thai",
      "ramen",
      "fajitas",
      "jackfruit",
      "linguine",
      "gnocchi",
      "stir fry",
      "dal",
      "casserole",
      "slow cooker",
      "enchiladas",
      "risotto",
      "sushi",
      "stroganoff",
      "noodles",
      "masala",
      "sloppy joes",
      "noodle salad",
      "1 pot",
      "katsu",
    ],
    snack: [
      "flapjacks",
      "cookies",
      "cake",
      "gelato",
      "toast",
      "doughnut",
      "pudding",
      "cheesecake",
      "bars",
      "cupcake",
      "fruit salad",
      "muffins",
    ],
    smoothie: [
      "green",
      "protein",
      "blueberry",
      "berry",
      "strawberry",
      "chocolate",
      "peanut butter",
      "mango",
      "smoothie bowl",
      "caramel",
      "tropical",
      "vanilla",

      "apple",
      "spice",
      "pumpkin",
      "banana",
      "cherry",
      "matcha",
      "kale",
      "ginger",
    ],
  };
}

export function unitsList() {
  return [
    {
      tsp: {
        synoynms: ["teaspoon", "teaspoons", "tsp.", "tsps"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      tbsp: {
        synoynms: ["tablespoon", "tablespoons", "tbs", "tb", "tbsp.", "tbsps"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      cup: {
        synoynms: ["cups", "c"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      ml: {
        synoynms: ["milliliters", "millilitres", "mls"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      pint: {
        synoynms: ["pt", "pint", "pints"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      litre: {
        synoynms: ["l", "liter", "litres", "liters"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    { dl: { synoynms: [], unit_type: "volume", quantifiable_unit: true } },
    { gl: { synoynms: [], unit_type: "volume", quantifiable_unit: true } },
    {
      dash: {
        synoynms: ["dashes"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      gallon: {
        synoynms: ["gallons", " gal", "gals"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      gill: {
        synoynms: ["gills"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      floz: {
        synoynms: ["fl oz", "fl. oz", "fl.oz"],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      quart: {
        synoynms: ["qt", "quart."],
        unit_type: "volume",
        quantifiable_unit: true,
      },
    },
    {
      oz: {
        synoynms: ["ounce", "ounces"],
        unit_type: "weight",
        quantifiable_unit: true,
      },
    },
    {
      g: {
        synoynms: ["gram", "grams"],
        unit_type: "weight",
        quantifiable_unit: true,
      },
    },
    {
      mg: {
        synoynms: ["mgs"],
        unit_type: "weight",
        quantifiable_unit: true,
      },
    },
    {
      lb: {
        synoynms: ["lbs", "pound", "pounds"],
        unit_type: "weight",
        quantifiable_unit: true,
      },
    },
    {
      kg: {
        synoynms: ["kg ", " kg"],
        unit_type: "weight",
        quantifiable_unit: true,
      },
    },
    {
      mm: {
        synoynms: ["mm ", "mm's", "millimetres", "millimeters"],
        unit_type: "size",
        quantifiable_unit: true,
      },
    },
    {
      cm: {
        synoynms: ["centimetre", "centimeters", "cm", "cm's", "cms"],
        unit_type: "size",
        quantifiable_unit: true,
      },
    },
    {
      inch: {
        synoynms: ["inches"],
        unit_type: "size",
        quantifiable_unit: true,
      },
    },
    {
      wedge: {
        synoynms: ["wedges"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      bunch: {
        synoynms: ["bunches"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      stalk: {
        synoynms: ["stalks"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      sprig: {
        synoynms: ["sprigs"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      clove: {
        synoynms: ["cloves"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      bulb: {
        synoynms: ["bulbs"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      rib: {
        synoynms: ["ribs"],
        unit_type: "specific_food_unit",
        quantifiable_unit: false,
      },
    },
    {
      "to serve": {
        synonyms: ["serve"],
        unit_type: "serving",
        quantifiable_unit: false,
      },
    },
  ];
}
